config/routes.rb
Rails.application.routes.draw do

	root "static_pages#home"

	scope "/:locale" do
  	devise_for :users
	end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  after_filter :prepare_unobtrusive_flash
  before_filter :set_locale

  private

  	def set_locale
      I18n.locale = params[:locale] || extract_locale_from_accept_language_header || I18n.default_locale
    end

		def default_url_options(options = {})
			{ locale: I18n.locale }.merge options
		end

    def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header_application.html.erb
<%= nav_bar fixed: :top, brand: "App", responsive: true do %>
    <%= menu_group do %>
    <% end %>
    <%= menu_group pull: :right do %>
        <% if current_user %>
            <%= drop_down t("user") do %>
            <%= menu_item t("edit_password"), edit_user_registration_path %>
                <%= menu_item t("log_out"), destroy_user_session_path, :method => "DELETE", :confirm => t("sure?") %>
            <% end %>
        <% else %>
            <%= drop_down t("sign_in") do %>
                <%= form_for :user, url: session_path(:user), :html => {class: "navbar-form pull-right form"} do |f| %>
                    <div class="form-group">
                        <label for="InputFieldA">email:</label>
                        <%= f.text_field :email, :class => "form-control" %>
                    </div>
                    <div class="form-group">
                        <label for="InputFieldA">password:</label>
                        <%= f.password_field :password, :class => "form-control" %>
                    </div>

                    <div class="form-group">
                        <p><%= f.check_box :remember_me %><%= t('remember_me') %></p>
                    </div>

                    <div class="form-group">
                        <%= f.submit t("sign_in", :default => "Sign in"), :class => "btn btn-primary" %> <%= t("or") %>
                        <%= link_to t("sign_up", :default => "Sign up"), new_user_registration_path, :class => "" %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
        <%= drop_down t("language") do %>
            <%= menu_item url_for(:locale => :es) do %>
                <%= image_tag "es.png" %> <%= t("spanish") %>
            <% end %>
            <%= menu_item url_for(:locale => :en) do %>
                <%= image_tag "en.png" %> <%= t("english") %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Base app" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= render "layouts/header_application" %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; Company 2016</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/static_pages/home.html.erb
dfghj